import { GraduationCap, Target, Users, ShieldCheck, Database, Cpu } from "lucide-react";
import { motion } from "framer-motion";
import PageWrapper from "../components/PageWrapper";

export default function About() {
  return (
    <PageWrapper className="relative">
      {/* Background styling for depth */}
      <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-[0.03] pointer-events-none" aria-hidden="true"></div>
      
      <div className="mx-auto max-w-5xl px-4 py-16 sm:py-24 relative z-10">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut" }}
          className="text-center mb-16"
        >
          <p className="mb-4 inline-flex items-center gap-2 rounded-full bg-civic-100 dark:bg-civic-900/30 px-3 py-1 text-xs font-bold uppercase tracking-widest text-civic-700 dark:text-civic-300">
            Learn More
          </p>
          <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 dark:text-white sm:text-6xl drop-shadow-sm">
            About OGRSA
          </h1>
          <p className="mt-6 text-xl leading-relaxed text-slate-600 dark:text-slate-400 font-medium max-w-3xl mx-auto">
            <strong className="text-civic-700 dark:text-civic-300">Online Grievance Redressal System Awareness (OGRSA)</strong> is a
            Community Engagement Project (CEP) developed as part of a BSc IT
            curriculum. Its twin goals are to <em>educate</em> citizens about how
            online grievance redressal works, and to <em>demonstrate</em> a fully
            functional grievance platform they can try hands-on.
          </p>
        </motion.div>

        <motion.div 
          initial="hidden"
          animate="visible"
          variants={{
            hidden: { opacity: 0 },
            visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
          }}
          className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3"
        >
          {[
            {
              icon: GraduationCap,
              title: "Educational Purpose",
              text: "This is a student project for learning and community awareness. It is not an official government portal and is not integrated with any government system. No real government statistics are shown — all figures are generated by this application.",
            },
            {
              icon: Target,
              title: "CEP Objectives",
              text: "Spread awareness about grievance redressal, promote digital literacy, encourage citizen participation, and demonstrate transparency, tracking and accountability in public service complaints.",
            },
            {
              icon: Users,
              title: "Who is it for?",
              text: "Ordinary citizens who want to understand the process, students studying e-governance, and evaluators reviewing the technical implementation of a complete full-stack system.",
            },
            {
              icon: ShieldCheck,
              title: "Privacy & Security",
              text: "Authentication is handled by Neon Auth — passwords are never stored by the application. Citizens can only access their own grievances, and public tracking reveals no personal information.",
            },
            {
              icon: Database,
              title: "Data Architecture",
              text: "All application data lives in Neon Serverless PostgreSQL with a normalized relational schema: profiles, grievances, status history, notifications, feedback, categories and attachments — with foreign keys, constraints and transactional updates.",
            },
            {
              icon: Cpu,
              title: "Technology",
              text: "React + Vite + Tailwind CSS frontend, Node.js + Express REST API, Drizzle ORM, Neon PostgreSQL and Neon Auth. Charts by Recharts, icons by Lucide.",
            },
          ].map(({ icon: Icon, title, text }) => (
            <motion.article 
              key={title} 
              variants={{
                hidden: { opacity: 0, y: 30 },
                visible: { opacity: 1, y: 0 }
              }}
              whileHover={{ y: -5 }}
              className="card p-8 group border-0 bg-white/60 dark:bg-slate-900/60 transition-all hover:shadow-xl hover:shadow-civic-900/5 dark:hover:shadow-civic-900/20 relative overflow-hidden"
            >
              <div className="absolute inset-0 bg-gradient-to-br from-civic-50/50 to-transparent dark:from-civic-900/10 dark:to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
              <span className="relative inline-flex rounded-2xl bg-civic-50 p-3.5 text-civic-600 transition-colors group-hover:bg-civic-600 group-hover:text-white dark:bg-civic-950 dark:text-civic-400 dark:group-hover:bg-civic-600 dark:group-hover:text-white shadow-sm">
                <Icon className="h-6 w-6" aria-hidden="true" />
              </span>
              <h2 className="relative mt-5 text-xl font-bold tracking-tight text-slate-900 dark:text-white">{title}</h2>
              <p className="relative mt-3 text-sm leading-relaxed text-slate-500 font-medium">
                {text}
              </p>
            </motion.article>
          ))}
        </motion.div>
      </div>
    </PageWrapper>
  );
}
