import { and, asc, count, desc, eq } from "drizzle-orm";
import { db, schema } from "../db/client.js";
import { ApiError } from "../utils/apiError.js";

const { categories, notifications, profiles, grievances, awarenessContent, attachments } =
  schema;

/* --------------------------------- auth/me -------------------------------- */

export async function me(req, res) {
  res.json({
    success: true,
    data: {
      profile: req.profile,
      authUser: { id: req.authUser.id, email: req.authUser.email },
    },
  });
}

/* --------------------------------- profile -------------------------------- */

export async function getProfile(req, res) {
  res.json({ success: true, data: req.profile });
}

export async function updateProfile(req, res) {
  // NOTE: role is intentionally NOT updatable here — no self-promotion.
  const [updated] = await db
    .update(profiles)
    .set({
      name: req.body.name,
      mobile: req.body.mobile || null,
      updatedAt: new Date(),
    })
    .where(eq(profiles.id, req.profile.id))
    .returning();
  res.json({ success: true, message: "Profile updated.", data: updated });
}

/* -------------------------------- categories ------------------------------ */

export async function listCategories(req, res) {
  // Public: active only. Admin (with ?all=1 + admin role) gets everything.
  const wantAll = req.query.all === "1" && req.profile?.role === "ADMIN";
  const rows = await db
    .select()
    .from(categories)
    .where(wantAll ? undefined : eq(categories.active, true))
    .orderBy(asc(categories.name));
  res.json({ success: true, data: rows });
}

export async function createCategory(req, res) {
  const [existing] = await db
    .select({ id: categories.id })
    .from(categories)
    .where(eq(categories.name, req.body.name))
    .limit(1);
  if (existing) throw ApiError.conflict("A category with this name already exists.");

  const [row] = await db
    .insert(categories)
    .values({
      name: req.body.name,
      description: req.body.description || null,
      active: req.body.active ?? true,
    })
    .returning();
  res.status(201).json({ success: true, message: "Category created.", data: row });
}

export async function updateCategory(req, res) {
  const [row] = await db
    .update(categories)
    .set({
      name: req.body.name,
      description: req.body.description || null,
      ...(req.body.active !== undefined ? { active: req.body.active } : {}),
      updatedAt: new Date(),
    })
    .where(eq(categories.id, req.params.id))
    .returning();
  if (!row) throw ApiError.notFound("Category not found");
  res.json({ success: true, message: "Category updated.", data: row });
}

/* ------------------------------ notifications ----------------------------- */

export async function listNotifications(req, res) {
  const [rows, [{ unread }]] = await Promise.all([
    db
      .select()
      .from(notifications)
      .where(eq(notifications.userId, req.profile.id))
      .orderBy(desc(notifications.createdAt))
      .limit(50),
    db
      .select({ unread: count() })
      .from(notifications)
      .where(
        and(eq(notifications.userId, req.profile.id), eq(notifications.isRead, false))
      ),
  ]);
  res.json({ success: true, data: { items: rows, unread: Number(unread) } });
}

export async function markNotificationRead(req, res) {
  const [row] = await db
    .update(notifications)
    .set({ isRead: true })
    .where(
      and(eq(notifications.id, req.params.id), eq(notifications.userId, req.profile.id))
    )
    .returning();
  if (!row) throw ApiError.notFound("Notification not found");
  res.json({ success: true, data: row });
}

export async function markAllNotificationsRead(req, res) {
  await db
    .update(notifications)
    .set({ isRead: true })
    .where(
      and(eq(notifications.userId, req.profile.id), eq(notifications.isRead, false))
    );
  res.json({ success: true, message: "All notifications marked as read." });
}

/* ------------------------------- public stats ----------------------------- */

export async function publicStats(_req, res) {
  const [statusRows, [{ citizens }]] = await Promise.all([
    db.select({ status: grievances.status, n: count() }).from(grievances).groupBy(
      grievances.status
    ),
    db
      .select({ citizens: count() })
      .from(profiles)
      .where(eq(profiles.role, "CITIZEN")),
  ]);
  const byStatus = Object.fromEntries(statusRows.map((r) => [r.status, Number(r.n)]));
  const total = statusRows.reduce((s, r) => s + Number(r.n), 0);
  res.json({
    success: true,
    // Clearly application-generated figures — not government statistics.
    data: {
      source: "Live figures generated by this educational OGRSA application",
      registered: total,
      resolved: byStatus.RESOLVED ?? 0,
      inProgress:
        (byStatus.IN_PROGRESS ?? 0) + (byStatus.UNDER_REVIEW ?? 0) + (byStatus.ASSIGNED ?? 0),
      citizens: Number(citizens),
    },
  });
}

/* ----------------------------- awareness content --------------------------- */

export async function listAwareness(req, res) {
  const wantAll = req.query.all === "1" && req.profile?.role === "ADMIN";
  const rows = await db
    .select()
    .from(awarenessContent)
    .where(wantAll ? undefined : eq(awarenessContent.active, true))
    .orderBy(asc(awarenessContent.displayOrder), asc(awarenessContent.createdAt));
  res.json({ success: true, data: rows });
}

export async function createAwareness(req, res) {
  const [row] = await db
    .insert(awarenessContent)
    .values({
      section: req.body.section,
      title: req.body.title,
      body: req.body.body,
      displayOrder: req.body.displayOrder ?? 0,
      active: req.body.active ?? true,
    })
    .returning();
  res.status(201).json({ success: true, message: "Content created.", data: row });
}

export async function updateAwareness(req, res) {
  const [row] = await db
    .update(awarenessContent)
    .set({
      section: req.body.section,
      title: req.body.title,
      body: req.body.body,
      displayOrder: req.body.displayOrder ?? 0,
      ...(req.body.active !== undefined ? { active: req.body.active } : {}),
      updatedAt: new Date(),
    })
    .where(eq(awarenessContent.id, req.params.id))
    .returning();
  if (!row) throw ApiError.notFound("Content not found");
  res.json({ success: true, message: "Content updated.", data: row });
}

/* -------------------------------- attachments ----------------------------- */

/** Download attachment — owner or admin only. */
export async function downloadAttachment(req, res, next) {
  const [att] = await db
    .select({
      id: attachments.id,
      storageKey: attachments.storageKey,
      fileName: attachments.fileName,
      mimeType: attachments.mimeType,
      ownerId: grievances.userId,
    })
    .from(attachments)
    .innerJoin(grievances, eq(attachments.grievanceId, grievances.id))
    .where(eq(attachments.id, req.params.id))
    .limit(1);

  if (!att) throw ApiError.notFound("Attachment not found");
  const isOwner = att.ownerId === req.profile.id;
  const isAdmin = req.profile.role === "ADMIN";
  if (!isOwner && !isAdmin) throw ApiError.notFound("Attachment not found");

  const { env } = await import("../config/env.js");
  const path = await import("node:path");
  const filePath = path.join(env.uploadDir, path.basename(att.storageKey));
  res.setHeader("Content-Type", att.mimeType);
  res.setHeader(
    "Content-Disposition",
    `inline; filename="${att.fileName.replace(/[^\w.\- ]/g, "_")}"`
  );
  res.sendFile(filePath, (err) => err && next(ApiError.notFound("File missing on disk")));
}
